language: go

go:
  - "1.10"

# Restrict to cloning only 1 commit.
git:
  depth: 1

sudo: false

addons:
  postgresql: "9.5"

install:
  - psql -U postgres -c "CREATE DATABASE arborist_test"
  - PGHOST=localhost PGPORT=5432 PGDATABASE=arborist_test PGUSER=postgres ./migrations/latest

script:
  - go test -v ./...
