language: go

go:
  - "1.10"

# Restrict to cloning only 1 commit.
git:
  depth: 1

sudo: false

addons:
  postgresql: "9.5"

env:
  global:
    - PGHOST=localhost
    - PGPORT=5432
    - PGUSER=postgres
    - PGDATABASE=arborist_test

install:
  - createdb
  - ./migrations/latest

script:
  - go test -v ./...
